export const filtersRef = [
  {
    name: "original",
    src: "/imgs/original.jpg",
    blur: 0,
    hue: 0,
    saturation: 0,
    luminance: 0,
    contrast: 0,
  },
  {
    name: "daily",
    src: "/imgs/daily.jpg",
    hue: 1,
    saturation: 0.16,
    luminance: 0.1,
    blur: 0,
    contrast: 2,
  },
  {
    name: "light",
    src: "/imgs/light.jpg",
    hue: 0,
    saturation: 0.18,
    luminance: 0.08,
    blur: 0,
    contrast: 0,
  },
  {
    name: "plain",
    src: "/imgs/plain.jpg",
    hue: 3.8,
    saturation: 0.08,
    luminance: 0.06,
    blur: 0,
    contrast: 0,
  },

  {
    name: "cream",
    src: "/imgs/cream.jpg",

    hue: 0,
    saturation: 0.18,
    luminance: 0.19,
    blur: 0,
    contrast: 0,
  },

  {
    name: "pure",

    src: "/imgs/pure.jpg",
    hue: 0,
    saturation: 0.04,
    luminance: 0.13,
    blur: 0,
    contrast: 0,
  },
  {
    name: "grayscale",
    src: "/imgs/grayscale.jpg",
    hue: 0,
    saturation: -5,
    luminance: -0.03,
    blur: 0,
    contrast: 0,
  },
  {
    name: "BS",
    src: "/imgs/BS.jpg",
    hue: 0,
    saturation: -0.13,
    luminance: 0.06,
    blur: 0,
    contrast: 0,
  },
  {
    name: "frozen",
    src: "/imgs/frozen.jpg",
    hue: 3.8,
    saturation: -0.38,
    luminance: 0.11,
    blur: 0,
    contrast: 0,
  },
  {
    name: "pretty",
    src: "/imgs/pretty.jpg",
    hue: 1.6,
    saturation: 0.09,
    luminance: 0.04,
    blur: 0,
    contrast: 10,
  },

  {
    name: "milk",
    src: "/imgs/milk.jpg",
    hue: 0,
    saturation: -0.21,
    luminance: -0.01,
    blur: 0,
    contrast: 0,
  },
  {
    name: "crystal",
    src: "/imgs/crystal.jpg",
    hue: 0,
    saturation: 0.04,
    luminance: 0.03,
    blur: 0,
    contrast: 0,
  },
  {
    name: "cloud",
    src: "/imgs/cloud.jpg",
    hue: 0,
    saturation: 0,
    luminance: -0.13,
    blur: 0,
    contrast: 0,
  },
  {
    name: "mood",
    src: "/imgs/mood.jpg",
    hue: 0,
    saturation: -0.04,
    luminance: -0.06,
    blur: 0,
    contrast: 0,
  },
  {
    name: "loveletter",
    src: "/imgs/loveletter.jpg",
    hue: 6.4,
    saturation: 0.21,
    luminance: 0.06,
    blur: 0,
    contrast: 0,
  },
  {
    name: "baby",
    src: "/imgs/baby.jpg",
    hue: 1.3,
    saturation: 0.19,
    luminance: 0.04,
    blur: 0,
    contrast: 0,
  },
  {
    name: "momo",
    src: "/imgs/momo.jpg",
    hue: 0,
    saturation: 0.47,
    luminance: 0.13,
    blur: 0,
    contrast: 0,
  },
  {
    name: "winter",
    src: "/imgs/winter.jpg",
    hue: 0,
    saturation: -0.34,
    luminance: 0.2,
    blur: 0,
    contrast: 26,
  },
  {
    name: "retro",
    src: "/imgs/retro.jpg",
    hue: 6.4,
    saturation: -0.07,
    luminance: 0.19,
    blur: 0,
    contrast: 3,
  },
  {
    name: "alight",
    src: "/imgs/alight.jpg",
    hue: 9.7,
    saturation: 0.46,
    luminance: 0.15,
    blur: 0,
    contrast: 8,
  },
  {
    name: "aurora",
    src: "/imgs/aurora.jpg",
    hue: 0,
    saturation: -0.09,
    luminance: -0.03,
    blur: 0,
    contrast: 23,
  },
  {
    name: "vintage",
    src: "/imgs/vintage.jpg",
    hue: 12.1,
    saturation: -0.22,
    luminance: -0.07,
    blur: 0,
    contrast: 16,
  },
  {
    name: "yummy",
    src: "/imgs/yummy.jpg",
    hue: 0,
    saturation: 0.38,
    luminance: -0.18,
    blur: 0,
    contrast: 0,
  },
  {
    name: "natural",
    src: "/imgs/natural.jpg",
    hue: 0,
    saturation: 0.18,
    luminance: 0.2,
    blur: 0,
    contrast: 12,
  },

  {
    name: "drama",
    src: "/imgs/drama.jpg",
    hue: 4.8,
    saturation: -3.38,
    luminance: 0.17,
    blur: 0,
    contrast: 17,
  },
  {
    name: "cute",
    src: "/imgs/cute.jpg",
    hue: 0,
    saturation: -0.12,
    luminance: 0.12,
    blur: 0,
    contrast: -1,
  },

  {
    name: "midnight",
    src: "/imgs/midnight.jpg",
    hue: 8.9,
    saturation: 0.66,
    luminance: -0.12,
    blur: 0,
    contrast: -15,
  },
  {
    name: "blossom",
    src: "/imgs/blossom.jpg",
    hue: 2.4,
    saturation: -0.18,
    luminance: 0.11,
    blur: 0,
    contrast: 24,
  },
  {
    name: "night",
    src: "/imgs/night.jpg",
    hue: 5.6,
    saturation: -0.39,
    luminance: -0.16,
    blur: 0,
    contrast: -16,
  },
  {
    name: "avatar",
    src: "/imgs/avatar.jpg",
    hue: 156.1,
    saturation: 0.15,
    luminance: 0.02,
    blur: 0,
    contrast: 5,
  },
];
